version: '3.3'

services:
  stable-diffusion:
    container_name: automatic1111-sd-webui
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ESRGAN:/app/ESRGAN:ro
      - ./repositories:/app/repositories:ro
      - ./src:/app/src:ro
      - cache:/home/webui/.cache
      - ./outputs:/app/outputs
      - ./runtime:/app/runtime
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  cache:
